### ISSUE TITLE
reduce redundancy in URL conversion.

### ISSUE THREAD

**Issue by zamhaq** [NJACKWinterOfCode/url-shortener#1]
Current behavior is that even if URL already exists in database, still a new entry is added. Reduce redundant URL's and return the shortened URL already in database.

**Comment by RishiRaj22** [comment]
I will like to work on this issue. However, I have an unrelated question:
I can't figure out if there is any way to check if two URLs are clashing or not.
The URL is generated based on probability. So, there must be a non-zero probability of the URLs clasing.
Is there any mechanism in place to handle it, or should I open another issue for it?

**Comment by zamhaq** [comment]
@RishiRaj22 Sorry,  I cannot understand you.

**Comment by RishiRaj22** [comment]
Currently the short url is based on 
`Math.floor(Math.random() * (now/10000000));`
Since, it just depends on random variable, for different URLs this term can be equal. How do you handle it? @zamhaq

**Comment by zamhaq** [comment]
@RishiRaj22 oh, that's the short URL no. being generated. What the issue specifies is to check if the longer url already exists in the database and return corresponding short URL.

**Comment by RishiRaj22** [comment]
Ya that's what I meant. Should I open an issue for that?

**Comment by zamhaq** [comment]
Oh yeah @RishiRaj22 you can create another isssue for that. Maybe we can use Pseudo random number generators.

**Comment by RishiRaj22** [comment]
@zamhaq Check PR #4
