### ISSUE TITLE
Remove the logins on the menu bar

### ISSUE THREAD

**Issue by haquezameer** [NJACKWinterOfCode/url-shortener#1]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request

**Current behavior:** 
The UI contains links for features not yet developed and thus not required.

![image](https://user-images.githubusercontent.com/20766601/49015391-fa3e8080-f1a8-11e8-861f-6c9ee3d1d7b2.png)

**Expected behavior:**

Remove the unnecessary links.

**Comment by sudipt1999** [comment]
can i claim the issue !
