### ISSUE TITLE
Add a route which serves a page to create short urls from the browser

### ISSUE THREAD

**Issue by rossoskull** [NJACKWinterOfCode/url-shortener#13]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request

**Current behavior:**
No route which serves this purpose. Project can only be used as an API.

**Expected behavior:**
When the user visits the created route, a webpage is served which helps them create the short url.

**Would you like to work on the issue?**
Yes

**Comment by rossoskull** [comment]
@zamhaq what are your views about this?

**Comment by haquezameer** [comment]
@rossoskull The project already has views for this. Visit `localhost:3000` on your browser. :+1:
