### ISSUE TITLE
update readme.md 

### ISSUE THREAD

**Issue by sourabhpruthi10** [NJACKWinterOfCode/url-shortener#17]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request

**Current behavior:**
readme.md contains step 1 and 3 which conveying the same info therefore redudant

**Expected behavior:**
the redundant step should be removed

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

```
Your operating system
Your node version
Additional information
```

**Would you like to work on the issue?**

```
Please let us know if you can work on it or the issue should be assigned to someone else.
```

**Comment by haquezameer** [comment]
Hi @sourabh1031 can you please paste the redundant instructions?

Are you talking about `npm install` and `npm start`?

**Comment by sourabhpruthi10** [comment]
@zamhaq sorry my bad i didn't read carefully the instructions. i opened the issue in a hurry. closing this for now.
