### ISSUE TITLE
Add  Auto Expiring Entries

### ISSUE THREAD

**Issue by haquezameer** [NJACKWinterOfCode/url-shortener#2]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request

**Current behavior:**
When user acesses `api/{shorturl}` endpoint then the database is first checked for any previous saved entries that match the `url` and if found user is redirected to that url. 

**Expected behavior:**
Add mechanism such that the entries expire after a certain amount of time such that if a user tries to accesses the same entry after the expired time then he is not routed to that url instead show a default `404` page.

**Comment by aggmoulik** [comment]
I am taking up this issue and I would like to know what is rnum in database..
