### ISSUE TITLE
UI design for the front-end and develop it.

### ISSUE THREAD

**Issue by zamhaq** [NJACKWinterOfCode/url-shortener#2]
The `API` can be called by other programs and can be used independently but the UX is not good.
Propose a `UI` design for the front-end in the comments and we will develop it. If any doubts, leave a comment mentioning me.

**Comment by RishiRaj22** [comment]
I have a couple of hours of free time now, so I guess I will work on this too.

**Comment by RishiRaj22** [comment]
![url-short](https://user-images.githubusercontent.com/19525514/34157439-7efcad1c-e4e7-11e7-8865-4fa5bde24fea.gif)
Is this fine?

**Comment by zamhaq** [comment]
@RishiRaj22 yeah maybe fine for now. We'll need to design it more. Anyways thanks. I will check it out later.

**Comment by RishiRaj22** [comment]
See #6
