### ISSUE TITLE
Update link to mongodb community in Readme

### ISSUE THREAD

**Issue by haquezameer** [NJACKWinterOfCode/url-shortener#21]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request

**Current behavior:**

The current link navigates to `mongodb atlas cloud`.

**Expected behavior:**

The correct link should navigate to [mongodb server community](https://www.mongodb.com/download-center/community) .

**Would you like to work on the issue?**
No.

**Comment by Sai-Adarsh** [comment]
I'm interested

**Comment by Sai-Adarsh** [comment]
@zamhaq dashboard isn't updated
