### ISSUE TITLE
Design and add a good looking web page which gets served when accessing a 404 route

### ISSUE THREAD

**Issue by haquezameer** [NJACKWinterOfCode/url-shortener#6]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request

**Current behavior:**

The current `404` route just sends a page with `404` text.
![screenshot_20181202_185249](https://user-images.githubusercontent.com/20766601/49340259-7e8a7b00-f663-11e8-94ff-cbc689ed9658.png)

**Expected behavior:**

Add a good looking web page that is served when `404` route is accessed.
You can get design inspiration from https://dribbble.com/search?q=404 or anywhere.

`P.S: Please do not copy the entire design. Just take some inspiration. You are free to unleash your creativity.` Cheers :clinking_glasses:

**Comment by Subhajit25Mondal** [comment]
i am solving the issue.
