### ISSUE TITLE
Creating a Logo for URL-shortener

### ISSUE THREAD

**Issue by rahulkumar082** [NJACKWinterOfCode/url-shortener#7]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request

**Current behavior:**
Currently we don't have any logo for our website

**Expected behavior:**
We will be having this Logo in our navigation bar
![logo](https://user-images.githubusercontent.com/21973996/34339990-e18df6f2-e9a1-11e7-936c-9dd41c4991a3.png)

 I would like to merge this logo with navigation bar.

**Comment by zamhaq** [comment]
@rahulkumar082 Great. Go ahead. :+1:
