### ISSUE TITLE
Remove the underline from the nav bar links on hover

### ISSUE THREAD

**Issue by sudipt1999** [NJACKWinterOfCode/url-shortener#8]
Its dosen't look good on nav bars so I would like to remove it!

**Comment by haquezameer** [comment]
@sudipt1999 please mention the issue your `PR` is fixing so that the issue can autoclose and also the issue has your `PR` reference which prevents others from working on the same issue. Thanks for your contributions. :100:

**Comment by sudipt1999** [comment]
Thank you sir !, I will keep that in mind sir from the next time.
